name: d4_scale_chromatic
version: 1.0.0
description: Sequential, diverging and categorical color scales.
repository: https://github.com/luizbarboza/d4_scale_chromatic

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  d4_color: ^1.0.0
  d4_interpolate: ^1.0.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.22.0